sudo: required
services:
  - docker

before_install:
  - docker build -t stevenroper/docker-react-demo -f Dockerfile.dev .

script:
  - docker run -e CI=true stevenroper/docker-react-demo npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react-demo"
  env: "Dockerreactdemo-env"
  bucket_name: "elasticbeanstalk-us-west-1-401458995882"
  bucket_path: "docker-react-demo"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY